---
output: 
  html_document
---

## **Building Maps with choropleth and ggplot**

---

**Data: Census 2000, number of jobs by industry by county**

```{r a, warning=FALSE, message=FALSE, comment=NA, R.options=list(width=100)}

library(choroplethr)
library(choroplethrMaps)
library(ggplot2)
library(gridExtra)

employment = read.csv("census_2000_employment.csv")
crops = read.csv("econ_census_2012_farming.csv")

head(employment)

```


```{r b, warning=FALSE, message=FALSE, comment=NA, R.options=list(width=100), fig.width=9, fig.height=5}

farming = data.frame(
  region = employment$STCOU,
  value = employment$Farming
  )

county_choropleth(farming, title = "Farming Employment", legend = "Jobs")


```

<br>

You can also change the color and create custom map objects

```{r c, warning=FALSE, message=FALSE, comment=NA, R.options=list(width=100), fig.width=9, fig.height=5}

choro = CountyChoropleth$new(farming)
choro$title = "Southern Farmers"
choro$set_num_colors(1)
choro$ggplot_scale = scale_fill_gradientn("Jobs Count", colors = c("#F6EAE1", "darkgreen"))
choro$set_zoom(c("texas", "louisiana", "mississippi", "alabama", "georgia", "arkansas", 
                 "tennessee", "south carolina", "florida", "oklahoma", "north carolina"))
choro$render()

## Also without the gradient
choro = CountyChoropleth$new(farming)
choro$title = "Southern Farmers"
choro$legend = "Jobs Count"
choro$set_zoom(c("texas", "louisiana", "mississippi", "alabama", "georgia", "arkansas", 
                 "tennessee", "south carolina", "florida", "oklahoma", "north carolina"))
choro$render()

```

Build separate maps for the types of crops

```{r d, warning=FALSE, message=FALSE, comment=NA, R.options=list(width=100), fig.width=9, fig.height=10}

## fill in NA with 0 to prevent NULL counties from standing out
crops[is.na(crops)] = 0

## create the individual data sets
corn = data.frame(region = crops$FIPS, value = crops$Corn)
wheat = data.frame(region = crops$FIPS, value = crops$Wheat)
cotton = data.frame(region = crops$FIPS, value = crops$Cotton)
peanuts = data.frame(region = crops$FIPS, value = crops$Peanuts)
peaches = data.frame(region = crops$FIPS, value = crops$Peaches)
oranges = data.frame(region = crops$FIPS, value = crops$Oranges)

## list of states we want on the map
states =  c("texas", "louisiana", "mississippi", "alabama", "georgia", "arkansas", 
            "tennessee", "south carolina", "florida", "oklahoma", "north carolina")

## create each graph object
g1 = CountyChoropleth$new(corn); g1$title = "Corn"; g1$set_num_colors(1); g1$set_zoom(states)
g2 = CountyChoropleth$new(wheat); g2$title = "Wheat"; g2$set_num_colors(1); g2$set_zoom(states)
g3 = CountyChoropleth$new(cotton); g3$title = "Cotton"; g3$set_num_colors(1); g3$set_zoom(states)
g4 = CountyChoropleth$new(peanuts); g4$title = "Peanuts"; g4$set_num_colors(1); g4$set_zoom(states)
g5 = CountyChoropleth$new(peaches); g5$title = "Peaches"; g5$set_num_colors(1); g5$set_zoom(states)
g6 = CountyChoropleth$new(oranges); g6$title = "Oranges"; g6$set_num_colors(1); g6$set_zoom(states)

## set colors that correspond to the crop
g1$ggplot_scale = scale_fill_gradientn("%", colors = c("gray", "yellow"))
g2$ggplot_scale = scale_fill_gradientn("%", colors = c("gray", "#F4A460"))
g3$ggplot_scale = scale_fill_gradientn("%", colors = c("gray", "white"))
g4$ggplot_scale = scale_fill_gradientn("%", colors = c("gray", "#D0B078"))
g5$ggplot_scale = scale_fill_gradientn("%", colors = c("gray", "#FFCBA4"))
g6$ggplot_scale = scale_fill_gradientn("%", colors = c("gray", "orange"))

## render each object in order to call as a group
g1 = g1$render(); g2 = g2$render(); g3 = g3$render()
g4 = g4$render(); g5 = g5$render(); g6 = g6$render()

grid.arrange(g1, g2, g3, g4, g5, g6, nrow = 3, ncol = 2)
```















