---
output: html_document
---

## **2 Two Way Factorial CRD**

---

#### Dataset
The response is the length of odontoblasts (cells responsible for tooth growth) in 60 guinea pigs. Each animal received one of three dose levels of vitamin C (0.5, 1, and 2 mg/day) by one of two delivery methods, (orange juice or ascorbic acid (a form of vitamin C and coded as VC).

```{r a, comment=NA, fig.width=8, fig.height=5}
library(plyr)

data("ToothGrowth")
head(ToothGrowth)
summary(ToothGrowth)

## Even observations per treatment group
table(ToothGrowth$supp, ToothGrowth$dose)

## ANOVA model
mdl = aov(len ~ supp * factor(dose), data = ToothGrowth)

summary(mdl)

```


**Interaction plot (Code not shown)**
```{r b, comment=NA, fig.width=8, fig.height=5, echo=FALSE}

## Calculate the mean and sd for each combination of supp and dose
x = ddply(ToothGrowth, .(supp, dose), summarize, mean = mean(len), sd = sd(len))

## add 95% confidence intervals
x$lwr = with(x, mean - qt(p = .975, df = 9) * sd/sqrt(10))
x$upr = with(x, mean + qt(p = .975, df = 9) * sd/sqrt(10))

x1 = subset(x, supp == "OJ")
x2 = subset(x, supp == "VC")

## Make a blank plot
plot(x = ToothGrowth$dose,
     y = ToothGrowth$len,
     xlab = "Dose",
     ylab = "Tooth Length",
     type = "n",
     ylim = c(6, 29),
     main = "Interaction Plot")

## Add points for the means
points(x = x1$dose, y = x1$mean, pch = 3, lwd = 4, col = "blue", cex = 1.1)
points(x = x2$dose, y = x2$mean, pch = 4, lwd = 4, col = "red", cex = 1.1)

## Add lines for interaction
lines(x = x1$dose, y = x1$mean, lty = 2)
lines(x = x2$dose, y = x2$mean, lty = 2)

## Add segments for confidence intervals
for (i in 1:6) {
  segments(x0 = x$dose[i], y0 = x$lwr[i], y1 = x$upr[i])
  segments(x0 = x$dose[i]-.05, x1 = x$dose[i]+.05, y0 = x$lwr[i])
  segments(x0 = x$dose[i]-.05, x1 = x$dose[i]+.05, y0 = x$upr[i])
}

## Add legend
legend("bottomright", c("Orange Juice", "Vitamin C"),
       pch = c(3, 4), bty = "n", cex = 1.1, col = c("blue", "red"))

```
