---
output: html_document
---

## **Hypothesis Testing**

---

##### **Techniques Used**
  * Shapiro Wilks Normality Test
  * T-Test
  * Calculating Power
  * Hypothesis Testing

---


```{r a1, comment=NA, fig.width=8, fig.height=7}
## QQ plot for normal distribution
set.seed(10)
x1 = rnorm(20)

## Are the data from a normal distribution?
shapiro.test(x1)     ## Shapiro-Wilk Test

mean(x1)

```

---

How does the sample mean compare to a hypothesis test that the true mean is 0? What is the power of the test? Check the power when the you reject the null.

$$H_0: \mu = 0, H_a: \mu \ne 0$$

|             | $H_0$ is True |  $H_a$ is True  |
|:-----------:|:-------------:|:--------------:|
|Accept $H_0$ |    Correct    |  Type II Error |
|Accept $H_a$ | Type I Error  |   Correct      |

```{r a3, comment=NA, warning=FALSE, message=FALSE}

## Is the true mean equal to 0? Verify the t statistic.
t.test(x1); (mean(x1) / sd(x1) * sqrt(length(x1)))

## We dont need to check the power of the test because we did not reject the null.
## Lets generate some data that will rejec the null

## Generate random data from N(1,1)
set.seed(10)
x2 = rnorm(20, mean = 1)

## Is the true mean equal to 0?
t.test(x2)

## Since we reject the null lets check the power of our test
power.t.test(n = length(x2), delta = mean(x2), sd = sd(x2), sig.level = .05,
             type = "one.sample", alternative = "two.sided", strict = TRUE)

```
